version: "1"

services:
  postgres:
    image: postgres
    container_name: event-management-postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db-event-management
    volumes:
      - data_postgres:/var/lib/postgresql/data

volumes:
  data_postgres:
